-- Wallet & P2P transfer schema.
-- Money is stored as integer paise (BIGINT) end to end: never float, never decimal rupees.

CREATE TABLE wallets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       VARCHAR(128) NOT NULL,
    balance_paise BIGINT       NOT NULL DEFAULT 0,
    version       BIGINT       NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_wallets_user_id UNIQUE (user_id),
    -- Hard backstop for the no-overdraft invariant: even a buggy write can never
    -- leave a negative balance; the DB rejects it.
    CONSTRAINT ck_wallets_balance_non_negative CHECK (balance_paise >= 0)
);

CREATE TABLE transfers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash    VARCHAR(64)  NOT NULL,
    from_wallet_id  BIGINT       NOT NULL REFERENCES wallets (id),
    to_wallet_id    BIGINT       NOT NULL REFERENCES wallets (id),
    amount_paise    BIGINT       NOT NULL,
    status          VARCHAR(16)  NOT NULL,
    decline_reason  VARCHAR(64),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- Exactly-once: a concurrent duplicate insert with the same key loses this race.
    CONSTRAINT uq_transfers_idempotency_key UNIQUE (idempotency_key),
    CONSTRAINT ck_transfers_amount_positive CHECK (amount_paise > 0),
    CONSTRAINT ck_transfers_distinct_wallets CHECK (from_wallet_id <> to_wallet_id)
);

CREATE INDEX ix_transfers_from_wallet_id ON transfers (from_wallet_id);
CREATE INDEX ix_transfers_to_wallet_id ON transfers (to_wallet_id);
